version: "3.8"
services:
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    networks:
      - app_network

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    networks:
      - app_network
    environment:
      - OLLAMA_HOST=http://ollama:11434
    depends_on:
      - ollama

  ollama:
    build: ./ollama
    ports:
      - "11434:11434"
    networks:
      - app_network
    volumes:
      - ollama_data:/root/.ollama
    deploy:
      resources:
        limits:
          memory: 8G

networks:
  app_network:
    driver: bridge

volumes:
  ollama_data:
    name: ollama_data
