name: Frontend Build
on:
  push:
    paths:
      - "frontend/package.json"
      - ".github/workflows/frontend.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install Dependencies
        run: |
          cd frontend
          bun install

      - name: Get version
        id: version
        run: |
          cd frontend
          VERSION=$(jq -r .version package.json)
          echo "VERSION=${VERSION}-$(date +'%Y%m%d')-$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build Frontend
        run: |
          cd frontend
          bun run build
          docker build -t frontend:${{ steps.version.outputs.VERSION }} . --build-arg VERSION=${{ steps.version.outputs.VERSION }}
          docker save frontend:${{ steps.version.outputs.VERSION }} | gzip > ../frontend.tar.gz
          echo ${{ steps.version.outputs.VERSION }} > ../version.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-image-${{ steps.version.outputs.VERSION }}
          path: |
            frontend.tar.gz
            version.txt
